### PR TITLE
Upgrade to jsPsych 7

### PR DESCRIPTION
**Pull request by jessestorbeck**
As with pushkin-consortium/pushkin-exptemplates-lexical#4 and pushkin-consortium/pushkin-exptemplates-grammatical#4, these changes bring the SPR template up to date with jsPsych 7 compatibility (based on the basic experiment template pushkin-consortium/pushkin-exptemplates-basic#39).

The experiment code has been cleaned up, and I added some new config options: comprehension questions (in the typical fashion for SPR experiments) and feedback (similar to the other templates). Notably, this new template uses a different SPR plugin than before. The new version uses [a plugin from jspsych-contrib](https://github.com/jspsych/jspsych-contrib/blob/main/packages/plugin-self-paced-reading/docs/jspsych-self-paced-reading.md), whereas the old template used a custom plugin.

I'm still testing things, but one issue I've noticed is that trials ("trials" in the strict jsPsych sense) governed by the SPR template cover the bottom part of the screen, which is visible during all other trials:

Screen Shot 2023-08-10 at 5 46 29 PM

Screen Shot 2023-08-10 at 5 46 41 PM

I'm not yet sure why this is happening. If we can't easily figure it out, there are probably other options for SPR plugins.

### CODE REVIEW

**Comment by jessestorbeck** [comment]
It seems that the SPR canvas size has to be hard-coded in the plugin's parameters. I set it to values that make sense for my display, and it looks decent now. I think it should work OK for most people, at least for demonstration purposes. I'm not sure how I'd feel about it if I were actually using it for data collection, but maybe it's good enough for now.

**Review by ayang21 — DISMISSED** [review]

**Comment by jessestorbeck** [comment]
I've fixed the issue with alignment of the SPR content with the rest of the experiment. The problem comes from the height of the jsPsychTarget div scaling to accommodate whatever content is in the experiment. This behavior is probably desirable for something like a survey, but it makes aligning content across trials challenging. What I did was fix the height of the jsPsychTarget div at the beginning of the experiment to 50% of the browser window. Then you can reliably size the SPR canvas and it aligns with the other text in the experiment. This same strategy fixes the issue of fixation cross alignment in the other templates.

The only remaining issue I'm encountering now is with the data. None of SPR trials or the comprehension questions end up in the database. I'm testing the other templates as well, and they also have missing data. I thought it might be that trials where the data parameter is directly modified weren't being logged, but I just tested that with a toy example in the basic template, and that doesn't seem to be the case. I'm still trying to track down exactly what's happening. I don't think the basic template has been substantively modified since I copied the code from there, but I'm checking the commit history there now to see if my template branches are missing anything.

**Comment by jessestorbeck** [comment]
I still don't know what's happening with entire trials being omitted from the data, but I did find in experimenting with the basic template that modifications to the data using an on_finish callback do not seem to make it into the data. I tried the timeline:

```
    const timeline = []

    var hello_trial_1 = {
        type: jsPsychHtmlKeyboardResponse,
        stimulus: 'Hello world!',
        choices: [' ']
    };

    var hello_trial_2 = {
        type: jsPsychHtmlKeyboardResponse,
        stimulus: 'Hello!',
        choices: [' '],
        data: { test: 'test' }
    };

    var hello_trial_3 = {
        type: jsPsychHtmlKeyboardResponse,
        stimulus: 'Hello world!',
        choices: [' '],
        data: { test: 'test' },
        on_finish: function (data) {
            if (data.test == 'test') {
                data.correct = true;
            } else {
                data.correct = false;
            }
        }
    };

    timeline.push(hello_trial_1, hello_trial_2, hello_trial_3);
```
And the data come out as follows, without the data.correct value for the third trial:
```
"{""rt"":748,""stimulus"":""Hello world!"",""response"":"" "",""trial_type"":""html-keyboard-response"",""trial_index"":0,""time_elapsed"":748,""internal_node_id"":""0.0-0.0"",""user_id"":""e7b61fc7-8a98-4c98-ae98-e97fa95233dd""}"
"{""rt"":394,""stimulus"":""Hello!"",""response"":"" "",""test"":""test"",""trial_type"":""html-keyboard-response"",""trial_index"":1,""time_elapsed"":1142,""internal_node_id"":""0.0-1.0"",""user_id"":""e7b61fc7-8a98-4c98-ae98-e97fa95233dd""}"
"{""rt"":353,""stimulus"":""Hello world!"",""response"":"" "",""test"":""test"",""trial_type"":""html-keyboard-response"",""trial_index"":2,""time_elapsed"":1496,""internal_node_id"":""0.0-2.0"",""user_id"":""e7b61fc7-8a98-4c98-ae98-e97fa95233dd""}"
```
Maybe this is a separate issue though. I checked the commit history for the basic template, and my template branches aren't missing anything besides the recent dependabot pulls (and I don't think these are even in the latest release of the basic template)

**Comment by jessestorbeck** [comment]
There's an issue for this now: pushkin-consortium/pushkin-client#38

**Comment by jkhartshorne** [comment]
Confirmed that the styling looks good, but that also it's not recording trial data.

**Comment by jkhartshorne** [comment]
Figured it out. This one has nested timelines. No on_finish is being added to interior timelines. 

The cheap but fail-dangerous method is to require people to run `setSaveAfterEveryStimulus()` on each timeline before nesting it into another one. But I think the better option is to have `setSaveAfterEveryStimulus()` check for nested timelines. It might be a little tricky though.

**Comment by jkhartshorne** [comment]
Most of this discussion moved to https://github.com/pushkin-consortium/pushkin-client/issues/38#issuecomment-1686643422

**Comment by ayang21** [comment]
Is this ready to merge?

**Comment by jessestorbeck** [comment]
@ayang21 -- No, we should wait until the updates to the jsPsych self-paced reading plugin go live. To that end, I'm going to convert this to a draft PR.

**Review by hunterschep — COMMENTED** [review]
Experiment template works with the current CLI & the new CLI branch (tested both) 

- All parts of the experiment in the frontend seem functional 
- Data is viewable in postgres 
- Question: is there any issue with discrepancies between when participants see each word? Since each word is triggered by the space bar, won't everyone press the space bar at different times, should there an option where each word comes out at lets say, half a second or something?

**Review by hunterschep — APPROVED** [review]
**changed to approve instead of comment** Experiment template works with the current CLI & the new CLI branch (tested both)

All parts of the experiment in the frontend seem functional
Data is viewable in postgres
Question: is there any issue with discrepancies between when participants see each word? Since each word is triggered by the space bar, won't everyone press the space bar at different times, should there an option where each word comes out at lets say, half a second or something?

**Pull request merged**
